// @generated by tools/generate_skill_states.py — do not edit by hand.
//
// Skills whose `State:` precondition Hercules checks in the shared switch at
// `skill.c:16453` and reports as cause 0 (`USESKILL_FAIL_LEVEL`), which is not
// what failed. The protocol has no code for most of these conditions, so the
// client names them from this table instead.
//
// Regenerate with: tools/generate_skill_states.py
//
// 42 skills across 13 states.

/// The precondition a skill declares in `skill_db.conf`, for the states whose
/// failure arrives as cause 0.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkillState {
    CartBoost,
    Falcon,
    Hiding,
    MHFighting,
    MHGrappling,
    MoonStance,
    QDShotReady,
    Riding,
    Shield,
    Sight,
    StarStance,
    SunStance,
    UniverseStance,
}

impl SkillState {
    /// What to tell the player when this precondition is the reason a skill
    /// would not cast.
    pub fn requirement(self) -> &'static str {
        match self {
            Self::CartBoost => "That needs Cart Boost active.",
            Self::Falcon => "That needs a falcon.",
            Self::Hiding => "That needs you to be hiding.",
            Self::MHFighting => "That needs your homunculus in fighting mode.",
            Self::MHGrappling => "That needs your homunculus in grappling mode.",
            Self::MoonStance => "That needs the Moon stance.",
            Self::QDShotReady => "That needs a Quick Draw Shot ready.",
            Self::Riding => "That needs you to be riding.",
            Self::Shield => "That needs a shield equipped.",
            Self::Sight => "That needs Sight active.",
            Self::StarStance => "That needs the Star stance.",
            Self::SunStance => "That needs the Sun stance.",
            Self::UniverseStance => "That needs the Universe stance.",
        }
    }
}

/// `(skill id, precondition)`, sorted by id. Consumed by `skill_failed_text`.
pub static SKILL_STATES: &[(u16, SkillState)] = &[
    (57, SkillState::Riding),            // KN_BRANDISHSPEAR
    (81, SkillState::Sight),             // WZ_SIGHTRASHER
    (129, SkillState::Falcon),           // HT_BLITZBEAT
    (130, SkillState::Falcon),           // HT_DETECTING
    (131, SkillState::Falcon),           // HT_SPRINGTRAP
    (137, SkillState::Hiding),           // AS_GRIMTOOTH
    (214, SkillState::Hiding),           // RG_RAID
    (249, SkillState::Shield),           // CR_AUTOGUARD
    (250, SkillState::Shield),           // CR_SHIELDCHARGE
    (251, SkillState::Shield),           // CR_SHIELDBOOMERANG
    (252, SkillState::Shield),           // CR_REFLECTSHIELD
    (257, SkillState::Shield),           // CR_DEFENDER
    (381, SkillState::Falcon),           // SN_FALCONASSAULT
    (480, SkillState::Shield),           // PA_SHIELDCHAIN
    (485, SkillState::CartBoost),        // WS_CARTTERMINATION
    (529, SkillState::Hiding),           // NJ_SHADOWJUMP
    (530, SkillState::Hiding),           // NJ_KIRIKAGE
    (1002, SkillState::Shield),          // CR_SHRINK
    (2310, SkillState::Shield),          // LG_SHIELDPRESS
    (2311, SkillState::Shield),          // LG_REFLECTDAMAGE
    (2315, SkillState::Shield),          // LG_SHIELDSPELL
    (2323, SkillState::Shield),          // LG_EARTHDRIVE
    (2559, SkillState::QDShotReady),     // RL_QD_SHOT
    (2574, SkillState::MoonStance),      // SJ_LIGHTOFMOON
    (2576, SkillState::MoonStance),      // SJ_FULLMOONKICK
    (2577, SkillState::StarStance),      // SJ_LIGHTOFSTAR
    (2579, SkillState::MoonStance),      // SJ_NEWMOONKICK
    (2580, SkillState::StarStance),      // SJ_FLASHKICK
    (2581, SkillState::UniverseStance),  // SJ_STAREMPEROR
    (2582, SkillState::UniverseStance),  // SJ_NOVAEXPLOSING
    (2584, SkillState::StarStance),      // SJ_FALLINGSTAR
    (2585, SkillState::UniverseStance),  // SJ_GRAVITYCONTROL
    (2586, SkillState::UniverseStance),  // SJ_BOOKOFDIMENSION
    (2587, SkillState::UniverseStance),  // SJ_BOOKOFCREATINGSTAR
    (2590, SkillState::SunStance),       // SJ_LIGHTOFSUN
    (2592, SkillState::SunStance),       // SJ_SOLARBURST
    (2593, SkillState::SunStance),       // SJ_PROMINENCEKICK
    (2594, SkillState::StarStance),      // SJ_FALLINGSTAR_ATK
    (2595, SkillState::StarStance),      // SJ_FALLINGSTAR_ATK2
    (8028, SkillState::MHFighting),      // MH_SONIC_CRAW
    (8036, SkillState::MHGrappling),     // MH_TINDER_BREAKER
    (8219, SkillState::Shield),          // ML_DEFENDER
];
