#!/usr/bin/env python3
"""Export player-facing quest names from Hercules (GPL-3.0-or-later).

Run after quest_db.conf changes; --check verifies the bundled table is current.
Names only: this does not invent objectives, rewards, or completion state.
"""

import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent


def export(source: str) -> str:
    # Preserve quoted strings while stripping both libconfig comment styles.
    source = re.sub(
        r'"(?:\\.|[^"\\])*"|/\*.*?\*/|//[^\n]*',
        lambda match: match[0] if match[0].startswith('"') else " ",
        source,
        flags=re.S,
    )
    entries = re.findall(r'\bId:\s*(\d+)\s+Name:\s*("(?:\\.|[^"\\])*")', source)
    ids = re.findall(r'\bId:\s*(\d+)', source)
    if not entries or len(entries) != len(ids):
        raise ValueError("Quest database format changed: not every quest has an adjacent Id and Name")
    names = {int(quest_id): json.loads(name) for quest_id, name in entries}
    if len(names) != len(entries):
        raise ValueError("Duplicate quest IDs in quest database")
    return "# Generated by tools/export_quest_names.py from Hercules/db/quest_db.conf (GPL-3.0-or-later).\n" + "".join(
        f"{quest_id}\t{' '.join(name.split())}\n" for quest_id, name in sorted(names.items())
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = export((ROOT.parent / "Hercules/db/quest_db.conf").read_text())
    output = ROOT / "korangar/src/world/library/quest_names.tsv"
    if args.check:
        if not output.exists() or output.read_text() != content:
            raise SystemExit("Quest names are stale; run tools/export_quest_names.py")
        print("Quest names are current")
    else:
        output.write_text(content)
        print(f"Exported {len(content.splitlines()) - 1} quest names")


if __name__ == "__main__":
    main()
