#!/usr/bin/env python3
"""Export Hercules job names to `hercules_job_names.tsv` for class labels.

Why: `JobName` reads the `JT_` constants out of `jobidentity.lub`, which are
*sprite* identities rather than class names. They are right for the classes
whose sprite folder matches the class ("Swordman", "Priest") and wrong for
every rebirth class, where Gravity kept the pre-rebirth name and suffixed it:
`JT_WIZARD_H` is job 4010, whom players and the server both call a **High
Wizard**, and `JT_MONK_H` is a Champion. A target frame reading "Monk H" is
not a name anyone recognises.

Hercules' own `db/constants.conf` names all 151 player jobs in English, and it
is the server this client actually connects to, so its names cannot drift from
the ids on the wire. This mirrors `hercules_item_names.tsv`: GRF table for
coverage, bundled Hercules names overlaid for the labels players read.

Two mechanical transforms, both applied to the constant name only:

  * `Job_High_Wizard` → `High Wizard` — drop the prefix, underscores to spaces.
    Hercules already capitalises these, so no case fixing is needed.
  * A trailing digit is a *mount view*, not a name: `Job_Knight2` (13) is a
    Knight on a peco, `Job_Paladin2` (4022) a Paladin on a grand peco. Both
    read as their class.

Usage:
    tools/export_job_names.py [--check]

    --check  exit 1 if the TSV is stale (for CI)
"""

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONSTANTS = REPO.parent / "Hercules" / "db" / "constants.conf"
OUTPUT = REPO / "korangar" / "src" / "world" / "library" / "hercules_job_names.tsv"

JOB_CONSTANT = re.compile(r"^\s*Job_([A-Za-z0-9_]+):\s*(\d+)\s*$")


def job_names(text):
    """id -> display name, first constant wins for a shared id."""
    names = {}
    for line in text.splitlines():
        match = JOB_CONSTANT.match(line)
        if not match:
            continue
        constant, job_id = match.group(1), int(match.group(2))
        # Trailing digit = mount view of the same class.
        name = re.sub(r"\d+$", "", constant).replace("_", " ").strip()
        if name and job_id not in names:
            names[job_id] = name
    return names


def render(names):
    lines = ["# Generated by tools/export_job_names.py from Hercules db/constants.conf.", "# id\tname"]
    lines.extend(f"{job_id}\t{name}" for job_id, name in sorted(names.items()))
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if the TSV is stale")
    args = parser.parse_args()

    if not CONSTANTS.exists():
        sys.exit(f"Hercules constants not found: {CONSTANTS}")

    names = job_names(CONSTANTS.read_text(encoding="utf-8", errors="replace"))
    if not names:
        sys.exit("no Job_ constants matched — has constants.conf changed shape?")

    rendered = render(names)

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            sys.exit(f"{OUTPUT.relative_to(REPO)} is stale — re-run tools/export_job_names.py")
        print(f"{OUTPUT.relative_to(REPO)} is up to date ({len(names)} jobs)")
        return

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)} ({len(names)} jobs)")


if __name__ == "__main__":
    main()
