#!/usr/bin/env python3
"""Generate `skill_states.rs` from Hercules' own `skill_db.conf`.

Why: Hercules checks a skill's `State:` precondition in one shared switch
(`skill.c:16453`) and reports every failure as `USESKILL_FAIL_LEVEL` — cause 0.
Twenty-one of the thirty-three states in that switch report cause 0, and only one
of them (`ST_SHIELD`) has a dedicated cause in the protocol at all; the other
twenty have neither a cause nor a message-table id. Gravity never numbered them,
so the official client says "Skill level is not high enough" too.

The client can still say something true, because the condition is *static*: which
skills need a shield, a cart, a falcon or a stance is written in `skill_db.conf`,
on disk, on both sides. The only thing missing was carrying it across to
`korangar-networking`, which renders the failure text and cannot read
`docs/skills.json` (that belongs to the `korangar` crate).

So this is the same move as `tools/generate_packet_lengths.sh` and
`tools/generate_message_table.py`: derive the table from the server rather than
hand-maintain a copy that silently rots when `skill_db.conf` changes. The
hand-written `SHIELD_SKILL_IDS` this replaces was already at that risk — nothing
would have told us if a skill gained or lost `State: "Shield"`.

**This covers preconditions only.** A cause 0 that means "the roll missed" or
"nobody was in range" is a *runtime* outcome, which no static table can carry;
those travel on `ZC_SKILL_FAIL_REASON` (0x0EFE) instead.

Re-run after any change to `skill_db.conf` or an upstream Hercules merge.

Usage:
    tools/generate_skill_states.py [HERCULES_DIR] [--check]

    --check  exit 1 if the generated table is stale, without writing (for CI)
"""

import json
import re
import sys
from pathlib import Path

# `State:` values whose failure Hercules reports as cause 0. Taken from the
# switch in `skill_check_condition_castbegin`: a state that sends a *specific*
# cause needs nothing from us, because the client already renders that cause.
#
# `MadoGear`, `Cart`, `ElementalSpirit`, `ExplosionSpirits`, `Dragon`, `InWater`,
# `NotOverWeight`, `PoisonWeapon`, `RollingCutter` and `Moveable` are deliberately
# absent for that reason — they map to causes 33, 55, 79, 74, 25, 13, 9, 32, 21
# and 10 respectively.
CAUSE_ZERO_STATES = {
    "Hiding",
    "Cloaking",
    "Hidden",
    "Riding",
    "PecoOn",
    "Falcon",
    "CartBoost",
    "Shield",
    "Sight",
    "RecoverWeightRate",
    "MoveEnable",
    "Water",
    "Wug",
    "RidingWug",
    "MH_Fighting",
    "MH_Grappling",
    "QD_Shot_Ready",
    "SunStance",
    "MoonStance",
    "StarStance",
    "UniverseStance",
}


def skill_blocks(text: str):
    """Yield each top-level skill block of a libconfig `skill_db.conf`."""
    depth, buffer = 0, []
    for line in text.split("\n"):
        if depth == 0:
            if line.strip() == "{":
                depth, buffer = 1, [line]
            continue
        buffer.append(line)
        depth += line.count("{") - line.count("}")
        if depth <= 0:
            yield "\n".join(buffer)
            depth = 0


def main() -> int:
    arguments = [argument for argument in sys.argv[1:] if argument != "--check"]
    check_only = "--check" in sys.argv
    hercules = Path(arguments[0] if arguments else "../Hercules")
    source = hercules / "db" / "re" / "skill_db.conf"
    if not source.is_file():
        print(f"error: {source} not found; is HERCULES_DIR correct?", file=sys.stderr)
        return 1

    rows: list[tuple[int, str, str]] = []
    for block in skill_blocks(source.read_text()):
        state = re.search(r'State:\s*"(\w+)"', block)
        if not state or state.group(1) not in CAUSE_ZERO_STATES:
            continue
        skill_id = re.search(r"Id:\s*(\d+)", block)
        name = re.search(r'Name:\s*"([A-Z0-9_]+)"', block)
        if not skill_id or not name:
            print(f"error: a skill block has State but no Id/Name:\n{block[:200]}", file=sys.stderr)
            return 1
        rows.append((int(skill_id.group(1)), name.group(1), state.group(1)))

    if not rows:
        print("error: no skills matched — has skill_db.conf's schema changed?", file=sys.stderr)
        return 1

    rows.sort()
    states = sorted({state for _, _, state in rows})
    out = Path(__file__).parent.parent / "korangar-networking" / "src" / "packet_versions" / "skill_states.rs"


    lines = [
        "// @generated by tools/generate_skill_states.py — do not edit by hand.",
        "//",
        "// Skills whose `State:` precondition Hercules checks in the shared switch at",
        "// `skill.c:16453` and reports as cause 0 (`USESKILL_FAIL_LEVEL`), which is not",
        "// what failed. The protocol has no code for most of these conditions, so the",
        "// client names them from this table instead.",
        "//",
        "// Regenerate with: tools/generate_skill_states.py",
        "//",
        f"// {len(rows)} skills across {len(states)} states.",
        "",
        "/// The precondition a skill declares in `skill_db.conf`, for the states whose",
        "/// failure arrives as cause 0.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum SkillState {",
    ]
    lines += [f"    {state.replace('_', '')}," for state in states]
    lines += [
        "}",
        "",
        "impl SkillState {",
        "    /// What to tell the player when this precondition is the reason a skill",
        "    /// would not cast.",
        "    pub fn requirement(self) -> &'static str {",
        "        match self {",
    ]
    lines += [f"            Self::{state.replace('_', '')} => {json.dumps(TEXT[state])}," for state in states]
    lines += [
        "        }",
        "    }",
        "}",
        "",
        "/// `(skill id, precondition)`, sorted by id. Consumed by `skill_failed_text`.",
        "pub static SKILL_STATES: &[(u16, SkillState)] = &[",
    ]
    entries = [(f"    ({skill_id}, SkillState::{state.replace('_', '')}),", name) for skill_id, name, state in rows]
    width = max(len(entry) for entry, _ in entries)
    lines += [f"{entry:<{width}}  // {name}" for entry, name in entries]
    lines += ["];", ""]

    generated = "\n".join(lines)
    if check_only:
        # A generated table only stays honest if something re-derives it. Without
        # this the file is just a hand-written list with a misleading banner.
        if not out.is_file() or out.read_text(encoding="utf-8") != generated:
            print(f"error: {out.name} is stale — re-run tools/generate_skill_states.py", file=sys.stderr)
            return 1
        print(f"{out.name} is up to date ({len(rows)} skills, {len(states)} states)")
        return 0

    out.write_text(generated, encoding="utf-8")
    # Match `cargo fmt` so generated-drift does not fight rustfmt on CI.
    import shutil
    import subprocess

    rustfmt_toml = Path(__file__).parent.parent / "rustfmt.toml"
    if shutil.which("rustfmt"):
        cmd = ["rustfmt"]
        if rustfmt_toml.is_file():
            cmd.append(f"--config-path={rustfmt_toml}")
        cmd.append(str(out))
        subprocess.run(cmd, check=False, capture_output=True)
    print(f"wrote {out} ({len(rows)} skills, {len(states)} states)")
    return 0


# Wording lives here rather than in the generated file so it is reviewable in a
# diff. Each is phrased as the requirement, not the failure, because the player
# is reading it to find out what to do next.
TEXT = {
    "CartBoost": "That needs Cart Boost active.",
    "Cloaking": "That needs you to be cloaked.",
    "Falcon": "That needs a falcon.",
    "MH_Fighting": "That needs your homunculus in fighting mode.",
    "MH_Grappling": "That needs your homunculus in grappling mode.",
    "MoonStance": "That needs the Moon stance.",
    "MoveEnable": "That needs you to be able to move.",
    "Hidden": "That needs you to be hidden.",
    "Hiding": "That needs you to be hiding.",
    "PecoOn": "That needs you to be mounted.",
    "QD_Shot_Ready": "That needs a Quick Draw Shot ready.",
    "RecoverWeightRate": "That needs your weight below 50%.",
    "Riding": "That needs you to be riding.",
    "RidingWug": "That needs you to be riding your warg.",
    "Shield": "That needs a shield equipped.",
    "Sight": "That needs Sight active.",
    "StarStance": "That needs the Star stance.",
    "SunStance": "That needs the Sun stance.",
    "UniverseStance": "That needs the Universe stance.",
    "Water": "That needs you to be standing in water.",
    "Wug": "That needs a warg.",
}


if __name__ == "__main__":
    raise SystemExit(main())
