#!/usr/bin/env python3
"""Generate `hercules_messages.tsv` from Hercules' own `messages_*.h`.

Why: `ZC_MSG` / `ZC_MSG_VALUE` / `ZC_MSG_SKILL` carry only a **message id**, and
the client resolves it through `msgstringtable.txt`. That file ships with the
*client* data, and ours is from a different build than the server: measured
2026-08-07, 1614 of the 4006 documented ids disagree with what Hercules means by
them and 433 are missing outright (the table is 3577 lines; the ids run past
4000).

Most disagreements are harmless rewording, but the drift is not uniform — some
regions are off by a line, which produces text that is not merely different but
*wrong*. The worst case found: a **successful** production skill (`MSG_SKILL_SUCCESS`,
0x626) resolved to "Item does not exist.", and a **failed** one resolved to
"Successful." — an inverted report.

Hercules documents the English gloss for every id in a comment right above it,
and those ids are exactly what the server sends, so the server's own header is
authoritative for this pairing. Same principle as
`tools/generate_packet_lengths.sh`: derive it from the server rather than hoping
the client data matches.

Korean-only glosses are skipped so the bundled msgstringtable — which is at least
in the player's language — stays the fallback for them.

Usage:
    tools/generate_message_table.py [HERCULES_DIR] [VARIANT]
"""

import re
import sys
from pathlib import Path

PACKETVER = 20220406
# Hangul is not the only script in the Korean slot — the element and size names
# are documented with the Chinese characters the client draws (`無`, `小`), so a
# Hangul-only test calls those lines English.
HANGUL = re.compile(r"[ᄀ-ᇿ⺀-鿿가-힯豈-﫿＀-￯]")
# A block documents the id for one or more *client version ranges*, newest
# first, each as `<range>` / `<korean>` / `<english>`:
#
#   /*20100525 to latest
#   아이템을 착용할 수 있는 레벨이 아닙니다.
#   You cannot equip this item with your current level.
#   20130807 to 20130814
#   해당 맵에서는 의상 장비가 보이지 않습니다.
#   Nothing found in the selected map.
#   */
#   MSG_CANNOT_EQUIP_ITEM_LEVEL = 0x6ed,
#
# Taking the last English line picks an **obsolete** range — that one would
# render "Nothing found in the selected map." for a level-too-low equip. Pick
# the range that covers the server's PACKETVER instead.
BLOCK = re.compile(
    # `(?:(?!\*/).)*` rather than `.*?`: a plain lazy body still swallows the
    # file's own licence header, whose `*/` is not followed by an id, and hands
    # `MSG_DO_YOU_AGREE` twenty lines of GPL.
    r"/\*(?P<body>(?:(?!\*/).)*)\*/\s*\n\s*(?P<name>MSG_\w+)\s*=\s*(?P<id>0x[0-9a-fA-F]+|\d+)\s*,",
    re.S,
)
RANGE = re.compile(r"^(?P<from>\d{8})\s+to\s+(?P<to>latest|\d{8})\s*$")

# Ids whose gloss in `messages_*.h` was **misaligned upstream** and corrected in
# the Hercules tree (2026-08-07) — see the fork-delta list in `CLAUDE.md` §3b.
# `messages_*.h` is banner-marked autogenerated, so a regeneration would drop
# those corrections, and the only symptom would be plausible, confidently wrong
# text arriving in chat again. This turns that into a failed run.
#
# 0x746 is the one a player meets: it is what an item still on its reuse delay
# reports, and it was rendering the macro-save message. 0x576 anchors the head of
# a thirteen-id run whose English lagged its Korean by one slot, and 0x582 the
# tail, whose own gloss had fallen off the end entirely.
CORRECTED_UPSTREAM = {
    0x576: "Holy water is required.",
    0x582: "Mobile authentication has failed.",
    0x745: "Content has been saved in [SaveData_ExMacro%d]",
    0x746: "%d seconds left until you can use",
}


def gloss_for(body: str, packetver: int) -> str | None:
    """English text of the version range covering `packetver`."""
    groups: list[tuple[int, int, list[str]]] = []
    current: tuple[int, int] | None = None
    for line in body.splitlines():
        line = line.strip()
        if not line:
            continue
        matched = RANGE.match(line)
        if matched:
            start = int(matched.group("from"))
            end = 99999999 if matched.group("to") == "latest" else int(matched.group("to"))
            current = (start, end)
            groups.append((start, end, []))
        elif groups:
            groups[-1][2].append(line)
        elif current is None:
            # No range header at all — a bare block documenting one text.
            groups.append((0, 99999999, [line]))

    # An open "to latest" range overlaps the narrow historical ones, so prefer
    # the most specific match rather than whichever is written first.
    for start, end, lines in sorted(groups, key=lambda group: group[1] - group[0]):
        if not (start <= packetver <= end):
            continue
        english = english_half(lines)
        if english:
            return " ".join(english)
    return None


def english_half(lines: list[str]) -> list[str]:
    """The English lines of one range.

    A range documents the same message twice, Korean first and English second,
    and **either half can span several lines** — `MSG_KEYCRYPT_INSTALL_KEYDRIVER`
    is three sentences in each language. Taking the last non-Korean line drops
    all but the closing fragment, which for
    `MSG_MDUNGEON_SUBSCRIPTION_ERROR_EXIST` leaves a bare "Please enter in 5
    minutes." with no idea what was entered.

    Splitting the range down the middle is what handles that, and it is also the
    only thing that handles the reverse case: 109 ranges have **no** Korean
    characters at all, because the Korean slot holds a romanisation or a command
    list ("Rouge" / "Rogue", "/pk on : pk On"). Scanning for the last
    Korean-script line would take both halves there and render "Rouge Rogue".
    """
    half = lines[len(lines) // 2 :] if len(lines) % 2 == 0 else lines
    # The halves are not always balanced — a two-line Korean text can be glossed
    # by one English line and vice versa, and a few ranges interleave the two
    # languages — so drop every Korean-script line the split leaves behind
    # rather than printing it at an English-speaking player.
    return [line for line in half if not HANGUL.search(line)]


def main() -> int:
    hercules = Path(sys.argv[1] if len(sys.argv) > 1 else "../Hercules")
    variant = sys.argv[2] if len(sys.argv) > 2 else "main"
    source = hercules / "src" / "map" / f"messages_{variant}.h"
    if not source.is_file():
        print(f"error: {source} not found", file=sys.stderr)
        return 1

    text = source.read_text(encoding="utf-8", errors="replace")
    rows: dict[int, str] = {}
    for match in BLOCK.finditer(text):
        gloss = gloss_for(match.group("body"), PACKETVER)
        # A Korean-only entry has no English line to take; leave it to the
        # client's own table rather than showing Korean to an English player.
        if not gloss:
            continue
        raw = match.group("id")
        message_id = int(raw, 16) if raw.startswith("0x") else int(raw)
        if message_id > 0xFFFF:
            continue
        rows.setdefault(message_id, gloss.replace("\t", " "))

    reverted = {mid: rows.get(mid) for mid, text in CORRECTED_UPSTREAM.items() if rows.get(mid) != text}
    if reverted:
        print(f"error: {source} has lost the gloss corrections — refusing to write a table that is wrong again", file=sys.stderr)
        for message_id, found in reverted.items():
            print(f"  0x{message_id:04x}  expected {CORRECTED_UPSTREAM[message_id]!r}\n            found    {found!r}", file=sys.stderr)
        print("Re-apply the delta recorded in korangar's CLAUDE.md §3b, then re-run.", file=sys.stderr)
        return 1

    out = Path(__file__).parent.parent / "korangar" / "src" / "world" / "library" / "hercules_messages.tsv"
    out.write_text("".join(f"{i}\t{t}\n" for i, t in sorted(rows.items())), encoding="utf-8")
    print(f"wrote {len(rows)} messages to {out.relative_to(out.parents[5])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
