#!/usr/bin/env bash
#
# Generate the authoritative packet-length table for a Hercules server build.
#
# Korangar frames incoming packets by deserialization: an unregistered packet
# desyncs the read buffer and drops everything after it. This script lets the C
# preprocessor evaluate Hercules' own `packetLen(id, len)` tables at the exact
# PACKETVER the server is compiled with, then emits a Rust length table that
# `PacketHandler::register_length_fallbacks` uses to consume any not-yet-modeled
# packet cleanly (see korangar-networking/src/packet_versions/lengths_20220406.rs).
#
# Re-run this after bumping the server's PACKETVER or updating Hercules.
#
# Usage:
#   tools/generate_packet_lengths.sh [HERCULES_DIR] [PACKETVER] [VARIANT]
#
#   HERCULES_DIR  Path to the Hercules_RO checkout (default: ~/GitHub/Hercules_RO)
#   PACKETVER     Server's compiled PACKETVER (default: 20190605, from mmo.h)
#   VARIANT       main | re | zero | sak | ad (default: main; matches a build
#                 with no ENABLE_PACKETVER_* flag set)
#
# The PACKETVER/VARIANT must match how the server is actually built. Verify with:
#   grep -n 'define PACKETVER' <HERCULES_DIR>/src/common/mmo.h
#   ./configure --help | grep -A1 packetver   # if a build override is used

set -euo pipefail

HERCULES_DIR="${1:-$HOME/GitHub/Hercules_RO}"
PACKETVER="${2:-20220406}"
VARIANT="${3:-main}"

SRC_DIR="$HERCULES_DIR/src"
OUT_FILE="$(dirname "$0")/../korangar-networking/src/packet_versions/lengths_20220406.rs"

if [[ ! -d "$SRC_DIR/common/packets" ]]; then
    echo "error: $SRC_DIR/common/packets not found; is HERCULES_DIR correct?" >&2
    exit 1
fi

# Pick the length-table entry point the way common/packets_len.h does, so the
# right yearly files (and version #if guards) are evaluated.
case "$VARIANT" in
    main) VARIANT_DEFINE="" ;;
    re)   VARIANT_DEFINE="-DPACKETVER_RE" ;;
    zero) VARIANT_DEFINE="-DPACKETVER_ZERO" ;;
    sak)  VARIANT_DEFINE="-DPACKETVER_SAK" ;;
    ad)   VARIANT_DEFINE="-DPACKETVER_AD" ;;
    *) echo "error: unknown VARIANT '$VARIANT'" >&2; exit 1 ;;
esac

# GNU mktemp has --suffix, BSD/macOS mktemp does not — create the file
# portably and rename it to get the .c extension cpp wants.
STUB_BASE="$(mktemp "${TMPDIR:-/tmp}/packet_lengths.XXXXXX")"
STUB="$STUB_BASE.c"
mv "$STUB_BASE" "$STUB"
trap 'rm -f "$STUB"' EXIT

# `packetLen` is a table-building macro in Hercules; redefine it to emit a clean
# marker line so we can scrape (id, len) pairs out of the preprocessor output.
printf '#define packetLen(id, len) PKTLEN id len\n#include "common/packets_len.h"\n' > "$STUB"

# `cc -E` instead of `cpp`: macOS's `cpp` is a wrapper that mangles arguments;
# this form works with both clang (macOS) and gcc (Linux/WSL).
TABLE="$(cc -E -x c -nostdinc -P -DPACKETVER="$PACKETVER" $VARIANT_DEFINE -I "$SRC_DIR" "$STUB" \
    | awk '/^PKTLEN/ { print $2, $3 }')"

COUNT="$(printf '%s\n' "$TABLE" | grep -c . || true)"
if [[ "$COUNT" -eq 0 ]]; then
    echo "error: no packet lengths extracted; check PACKETVER/VARIANT/paths" >&2
    exit 1
fi

{
    echo "// @generated by tools/generate_packet_lengths.sh — do not edit by hand."
    echo "//"
    echo "// Authoritative on-wire packet lengths from Hercules at PACKETVER=$PACKETVER"
    echo "// (variant: $VARIANT). Each entry is (header, length); length is the total"
    echo "// packet size including the 2-byte header, or -1 for variable-length packets"
    echo "// (whose real size is read from the 2-byte length field after the header)."
    echo "//"
    echo "// Regenerate with: tools/generate_packet_lengths.sh"
    echo "//"
    echo "// Total packets in this table: $COUNT."
    echo
    echo "/// (header, total length or -1 for variable) for every packet the server"
    echo "/// build knows how to frame. Consumed by"
    echo "/// [\`ragnarok_packets::handler::PacketHandler::register_length_fallbacks\`]."
    echo "pub static PACKET_LENGTHS: &[(u16, i32)] = &["
    printf '%s\n' "$TABLE" | while read -r id len; do
        printf '    (0x%04X, %s),\n' "$id" "$len"
    done
    echo "];"
} > "$OUT_FILE"

echo "wrote $OUT_FILE ($COUNT packets, PACKETVER=$PACKETVER, variant=$VARIANT)"
